# arxivの学問領域の指定
subject: 'cs'
#stat
# 検索キーワード

#keywords:
        #kaggle: 3
        #resnet: 3
        #anomaly detection: 1


keywords:
    sound: 1
    audio: 1
    sound feature: 3
    audio feature: 3
    noise removal: 2
    spectrogram: 3
